### ISSUE TITLE
Some examples in tutorial are not working

### ISSUE THREAD

**Issue by ForestRupicolous** [LaboratoireMecaniqueLille/crappy#41]
Hi,
thank you for providing this package. It looks very promising.
I'm currently trying the tutorial using Python 3.11 and crappy 1.5.10 but with the code example in [3a-loops](https://crappy.readthedocs.io/en/v1.5.10/tutorials/gettingstarted.html#a-loops) I get following error:
`TypeError: Ramp.__init__() got an unexpected keyword argument 'cmd'`
When I fix it by removing the `'cmd': 0` part, I get another error: `TypeError: cannot unpack non-iterable float object`. For me it looks like the examples at this point where not updated to fit the current version 1.5.10.
If needed I can provide additonal information or test any updates.

Thanks

**Comment by WeisLeDocto** [comment]
Hi !

You are absolutely right, the example code you mention contained two distinct errors.
They should be fixed on the web documentation as soon as ReadTheDocs is done rebuilding it.
Sorry for the inconvenience, and thank you for signaling it !

FYI I'm currently working on a version `2.0.0` of Crappy, that should be released in a month or two.
I mainly worked on improving the stability compared to the `1.5.x` versions, with also a much better handling of the cameras.
All that's missing is an in-depth refactoring of the documentation, but the code and examples are mostly ready.
If you want to check it, it's in the `develop` branch of the repo. It can also be installed with `pip` as the version `2.0.0.dev2` (dev3 available this week).

Weis
